# Generated by Django 4.2.4 on 2023-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=100)),
                ('project_subject', models.CharField(max_length=350)),
                ('project_description', models.CharField(max_length=700)),
                ('client_firstname', models.CharField(max_length=100)),
                ('client_lastname', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=100)),
                ('project_link', models.CharField(max_length=500)),
            ],
        ),
    ]
